cat << 'EOF' > .github/workflows/deploy.yml
name: Deploy Eleventy + Tailwind to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write         # Permite al action hacer push

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Usa GITHUB_TOKEN para push

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build CSS & HTML
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: main      # Publica en main, no gh-pages
EOF
